### Repo samples:

* Main PG repo: https://github.com/Azure-Samples/document-intelligence-code-samples
* Additional repo: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/documentintelligence/azure-ai-documentintelligence/samples
* Previous Forms recognizer repo: https://github.com/microsoft/Form-Recognizer-Toolkit

## Import libraries:

In [30]:
from azure.core.credentials import AzureKeyCredential
from azure.ai.documentintelligence import DocumentIntelligenceClient
from azure.ai.documentintelligence.models import AnalyzeDocumentRequest, ContentFormat,DocumentAnalysisFeature,AnalyzeOutputOption,AnalyzeResult
from azure.ai.documentintelligence.models import DocumentTable
from langchain.text_splitter import MarkdownHeaderTextSplitter
import os
import pandas as pd

from dotenv import load_dotenv
load_dotenv(override=True)

AZURE_DOC_INTELLIGENCE_ENDPOINT = os.environ["AZURE_DOC_INTELLIGENCE_ENDPOINT"]
AZURE_DOC_INTELLIGENCE_KEY = os.environ["AZURE_DOC_INTELLIGENCE_KEY"]

In [7]:
document_intelligence_client = DocumentIntelligenceClient(endpoint=AZURE_DOC_INTELLIGENCE_ENDPOINT, credential=AzureKeyCredential(AZURE_DOC_INTELLIGENCE_KEY), api_version="2024-11-30")

## Sample Image:

In [23]:
image_url = "https://github.com/Azure-Samples/document-intelligence-code-samples/blob/main/Data/layout/layout-finacialreport.png?raw=true"

poller = document_intelligence_client.begin_analyze_document("prebuilt-layout",
                                                             AnalyzeDocumentRequest(url_source=image_url),
                                                             output_content_format=ContentFormat.MARKDOWN)

result: AnalyzeResult = poller.result()
print(result.content)

# Beacon Roofing Supply, Inc. Notes to Consolidated Financial Statements Year Ended September 30, 2010 (dollars in thousands, except per share data or as otherwise indicated)


## 5. Prepaid Expenses and Other Current Assets

The significant components of prepaid expenses and other current assets were as follows:


<table>
<tr>
<th></th>
<th>September 30, 2010</th>
<th>September 30, 2009</th>
</tr>
<tr>
<td>Vendor rebates</td>
<td>$34.538</td>
<td>$38,857</td>
</tr>
<tr>
<td>Refundable income taxes</td>
<td>3,846</td>
<td>3,545</td>
</tr>
<tr>
<td>Other.</td>
<td>4.731</td>
<td>10,312</td>
</tr>
<tr>
<td></td>
<td>$43,115</td>
<td>$52,714</td>
</tr>
<tr>
<td>6. Property and Equipment, net</td>
<td></td>
<td></td>
</tr>
</table>


Property and equipment, net, consisted of the following:


<table>
<tr>
<th></th>
<th>September 30, 2010</th>
<th>September 30, 2009</th>
</tr>
<tr>
<td>Land</td>
<td>$ 3.056</td>
<td>$ 3,190</td>
</tr>
<tr>
<td>Buildings and leasehold improvements</td>
<td>19,987</td>
<td>18,725</td>
</tr>
<tr>
<td>Equipment</td>
<td>107.548</td>
<td>100,731</td>
</tr>
<tr>
<td>Furniture and fixtures.</td>
<td>10,936</td>
<td>10.478</td>
</tr>
<tr>
<td></td>
<td>141.527</td>
<td>1.33,124</td>
</tr>
<tr>
<td>Less: accumulated depreciation and amortization</td>
<td>93.776</td>
<td>80,159</td>
</tr>
<tr>
<td></td>
<td>$ 47.751</td>
<td>$ 52.965</td>
</tr>
</table>


Depreciation and amortization of property and equipment totaled $17,077, $17,389 and $18,381 in 2010,
2009 and 2008, respectively.


## 7. Accrued Expenses

The significant components of accrued expenses were as follows:


<table>
<tr>
<th></th>
<th>September 30. 2010</th>
<th>September 30, 2009</th>
</tr>
<tr>
<td>Uninvoiced inventory receipts</td>
<td>$ 7,739</td>
<td>$19,970</td>
</tr>
<tr>
<td>Employee-related accruals.</td>
<td>13,498</td>
<td>18,736</td>
</tr>
<tr>
<td>Unrealized loss on financial derivatives.</td>
<td>11,084</td>
<td>12,348</td>
</tr>
<tr>
<td>Other.</td>
<td>17,811</td>
<td>24,482</td>
</tr>
<tr>
<td></td>
<td>$50,132</td>
<td>$75.536</td>
</tr>
<tr>
<td>8. Financing Arrangements</td>
<td></td>
<td></td>
</tr>
</table>


### Senior Secured Credit Facilities

On November 2, 2006, the Company entered into an amended and restated seven-year $500 million
U.S. senior secured credit facility and a CS15 million senior secured Canadian credit facility with GE Antares
Capital ("GE Antares") and a syndicate of other lenders (combined, the "Credit Facility"). The Credit
Facility provides for a cash receipts lock-box arrangement that gives the Company sole control over the funds
in lock-box accounts, unless excess availability is less than $10 million or an event of default occurs, in which
case the senior secured lenders would have the right to take control over such funds and to apply such funds
to repayment of the senior debt.

<!-- PageNumber="52" -->

### Page extraction Functions

In [9]:
def table_to_html(table):
    table_html = "<table>"
    rows = [
        sorted([cell for cell in table.cells if cell.row_index == i], key=lambda cell: cell.column_index)
        for i in range(table.row_count)
    ]
    for row_cells in rows:
        table_html += "<tr>"
        for cell in row_cells:
            tag = "th" if (cell.kind == "columnHeader" or cell.kind == "rowHeader") else "td"
            cell_spans = ""
            if cell.column_span is not None and cell.column_span > 1:
                cell_spans += f" colSpan={cell.column_span}"
            if cell.row_span is not None and cell.row_span > 1:
                cell_spans += f" rowSpan={cell.row_span}"
            table_html += f"<{tag}{cell_spans}>{html.escape(cell.content)}</{tag}>"
        table_html += "</tr>"
    table_html += "</table>"
    return table_html

def text_html_processing(OcrExtractionDIOutput):
    offset = 0
    page_map = []
    page_map_dict =[]

    for page_num, page in enumerate(OcrExtractionDIOutput.pages):
        tables_on_page = [
            table
            for table in (OcrExtractionDIOutput.tables or [])
            if table.bounding_regions and table.bounding_regions[0].page_number == page_num + 1
        ]
        #print(tables_on_page)

        # mark all positions of the table spans in the page
        page_offset = page.spans[0].offset
        page_length = page.spans[0].length
        table_chars = [-1] * page_length
        for table_id, table in enumerate(tables_on_page):
            for span in table.spans:
                # replace all table spans with "table_id" in table_chars array
                for i in range(span.length):
                    idx = span.offset - page_offset + i
                    if idx >= 0 and idx < page_length:
                        table_chars[idx] = table_id

        # build page text by replacing characters in table spans with table html
        page_text = ""
        added_tables = set()
        for idx, table_id in enumerate(table_chars):
            if table_id == -1:
                page_text += OcrExtractionDIOutput.content[page_offset + idx]
            elif table_id not in added_tables:
                page_text += table_to_html(tables_on_page[table_id])
                added_tables.add(table_id)

        page_text += " "
        page_map.append((page_num+1, offset, page_text))

        single_page_dict = {}
        single_page_dict['page_num']= page_num+1
        single_page_dict['content'] = page_text
        single_page_dict['offset'] = offset
        page_map_dict.append(single_page_dict)

        offset += len(page_text)

    return page_map_dict

### Page extraction Function

In [14]:
def OcrExtractionDI(relative_path: str, Markdown: [bool]=True):
    
    path_to_document = os.path.abspath(
        os.path.join(relative_path))
    
    if Markdown==True:
        output_format = ContentFormat.MARKDOWN
    else:
        output_format = None

    with open(path_to_document, "rb") as f:
        poller = document_intelligence_client.begin_analyze_document("prebuilt-layout", 
                                                                    analyze_request=f, content_type="application/octet-stream", 
                                                                    output_content_format=output_format)
    OcrExtractionDIOutput: AnalyzeResult = poller.result()    
    
    if Markdown==False:
        pagemap = text_html_processing(OcrExtractionDIOutput)
        extracted_processed_text = pagemap
    else:
        extracted_processed_text = OcrExtractionDIOutput

    return extracted_processed_text

In [24]:
Extracted_data =  OcrExtractionDI("../layout-pageobject.png",Markdown=True)
print(Extracted_data.content)

<!-- PageHeader="This is the header of the document." -->


# This is title


## 1. Text

Latin refers to an ancient Italic language
originating in the region of Latium in
ancient Rome.


## 2. Page Objects


### 2.1 Table

Here's a sample table below, designed to
be simple for easy understand and quick
reference.


<table>
<caption>Table 1: This is a dummy table</caption>
<tr>
<th>Name</th>
<th>Corp</th>
<th>Remark</th>
</tr>
<tr>
<td>Foo</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Bar</td>
<td>Microsoft</td>
<td>Dummy</td>
</tr>
</table>


## 2.2. Figure


<figure>
<figcaption>Figure 1: Here is a figure with text</figcaption>

Values

500

450

100

400

350

300

300

250

200

200

200-

n

Jan

Feb

Mar

İçr

May

2um

Meness

</figure>


## 3. Others

Al Document Intelligence is an Al service
that applies advanced machine learning
to extract text, key-value pairs, tables,
and structures from documents
automatically and accurately:
☒
clear

☒
precise

☐
vague

☒
coherent

☐
Incomprehensible

Turn documents into usable data and
shift your focus to acting on information
rather than compiling it. Start with
prebuilt models or create custom models
tailored to your documents both on
premises and in the cloud with the Al
Document Intelligence studio or SDK.

Learn how to accelerate your business
processes by automating text extraction
with Al Document Intelligence. This
webinar features hands-on demos for key
use cases such as document processing,
knowledge mining, and industry-specific
Al model customization.

<!-- PageFooter="This is the footer of the document." -->
<!-- PageNumber="1 | Page" -->

In [25]:
Extracted_data =  OcrExtractionDI("../10K-MSFT-07-27-2023.pdf",Markdown=True)
print(Extracted_data.content)

# UNITED STATES SECURITIES AND EXCHANGE COMMISSION Washington, D.C. 20549 FORM 10-K

☒
☒
ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934
For the Fiscal Year Ended June 30, 2023
OR

☐
☐
TRANSITION REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934
For the Transition Period From
to

Commission File Number 001-37845


# MICROSOFT CORPORATION


<table>
<tr>
<th>WASHINGTON</th>
<th>91-1144442</th>
</tr>
<tr>
<td>(STATE OF INCORPORATION)</td>
<td>(I.R.S. ID)</td>
</tr>
</table>


ONE MICROSOFT WAY, REDMOND, WASHINGTON 98052-6399
(425) 882-8080
www.microsoft.com/investor

Securities registered pursuant to Section 12(b) of the Act:


<table>
<tr>
<th>Title of each class</th>
<th>Trading Symbol</th>
<th>Name of exchange on which registered</th>
</tr>
<tr>
<td>Common stock, $0.00000625 par value per share</td>
<td>MSFT</td>
<td>NASDAQ</td>
</tr>
<tr>
<td>3.125% Notes due 2028</td>
<td>MSFT</td>
<td>NASDAQ</td>
</tr>
<tr>
<td>2.625% Notes due 2033</td>
<td>MSFT</td>
<td>NASDAQ</td>
</tr>
</table>


Securities registered pursuant to Section 12(g) of the Act:

None

Indicate by check mark if the registrant is a well-known seasoned issuer, as defined in Rule 405 of the Securities Act. Yes
☒ ☐
No

Indicate by check mark if the registrant is not required to file reports pursuant to Section 13 or Section 15(d) of the Act. Yes
☐

☒
No

Indicate by check mark whether the registrant (1) has filed all reports required to be filed by Section 13 or 15(d) of the Securities Exchange Act of 1934 during the preceding 12
months (or for such shorter period that the registrant was required to file such reports), and (2) has been subject to such filing requirements for the past 90 days. Yes
☒ ☐
No

Indicate by check mark whether the registrant has submitted electronically every Interactive Data File required to be submitted pursuant to Rule 405 of Regulation S-T (§232.405 of
this chapter) during the preceding 12 months (or for such shorter period that the registrant was required to submit such files). Yes
☐
No
☒
Indicate by check mark whether the registrant is a large accelerated filer, an accelerated filer, a non-accelerated filer, a smaller reporting company, or an emerging growth company.
See the definitions of "large accelerated filer," "accelerated filer," "smaller reporting company," and "emerging growth company" in Rule 12b-2 of the Exchange Act.

Large Accelerated Filer
☒
Non-accelerated Filer
☐

Accelerated Filer
☐
Smaller Reporting Company
☐

Emerging Growth Company
☐

If an emerging growth company, indicate by check mark if the registrant has elected not to use the extended transition period for complying with any new or revised financial
accounting standards provided pursuant to Section 13(a) of the Exchange Act.
☐
☐

Indicate by check mark whether the registrant has filed a report on and attestation to its management's assessment of the effectiveness of its internal control over financial reporting
under Section 404(b) of the Sarbanes-Oxley Act (15 U.S.C. 7262(b)) by the registered public accounting firm that prepared or issued its audit report.
☒
☒

If securities are registered pursuant to Section 12(b) of the Act, indicate by check mark whether the financial statements of the registrant included in the filing reflect the correction of
an error to previously issued financial statements.
☐
☐

Indicate by check mark whether any of those error corrections are restatements that required a recovery analysis of incentive-based compensation received by any of the registrant's
executive officers during the relevant recovery period pursuant to §240.10D-1(b).
☐
☐

Indicate by check mark whether the registrant is a shell company (as defined in Rule 12b-2 of the Act). Yes
☐
No

☒

As of December 31, 2022, the aggregate market value of the registrant's common stock held by non-affiliates of the registrant was $1.8 trillion based on the closing sale price as
reported on the NASDAQ National Market System. As of July 24, 2023, there were 7,429,763,722 shares of common stock outstanding.


## DOCUMENTS INCORPORATED BY REFERENCE

Portions of the definitive Proxy Statement to be delivered to shareholders in connection with the Annual Meeting of Shareholders to be held on December 7, 2023 are incorporated by
reference into Part III.

<!-- PageBreak -->


## MICROSOFT CORPORATION FORM 10-K For the Fiscal Year Ended June 30, 2023 INDEX


<table>
<tr>
<th colspan="2"></th>
<th></th>
<th>Page</th>
</tr>
<tr>
<td colspan="2">PART I</td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td>Item 1.</td>
<td>Business</td>
<td>4</td>
</tr>
<tr>
<td colspan="2"></td>
<td>Information about our Executive Officers</td>
<td>20</td>
</tr>
<tr>
<td colspan="2">Item 1A.</td>
<td>Risk Factors</td>
<td>23</td>
</tr>
<tr>
<td colspan="2">Item 1B.</td>
<td>Unresolved Staff Comments</td>
<td>37</td>
</tr>
<tr>
<td colspan="2">Item 2.</td>
<td>Properties</td>
<td>37</td>
</tr>
<tr>
<td colspan="2">Item 3.</td>
<td>Legal Proceedings</td>
<td>37</td>
</tr>
<tr>
<td></td>
<td>Item 4.</td>
<td>Mine Safety Disclosures</td>
<td>37</td>
</tr>
<tr>
<td colspan="2">PART II</td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td>Item 5.</td>
<td>Market for Registrant's Common Equity, Related Stockholder Matters, and Issuer Purchases of Equity Securities</td>
<td>38</td>
</tr>
<tr>
<td></td>
<td>Item 6.</td>
<td>[Reserved]</td>
<td>39</td>
</tr>
<tr>
<td colspan="2">Item 7.</td>
<td>Management's Discussion and Analysis of Financial Condition and Results of Operations</td>
<td>40</td>
</tr>
<tr>
<td colspan="2">Item 7A.</td>
<td>Quantitative and Qualitative Disclosures about Market Risk</td>
<td>57</td>
</tr>
<tr>
<td colspan="2">Item 8.</td>
<td>Financial Statements and Supplementary Data</td>
<td>58</td>
</tr>
<tr>
<td colspan="2">Item 9.</td>
<td>Changes in and Disagreements with Accountants on Accounting and Financial Disclosure</td>
<td>99</td>
</tr>
<tr>
<td colspan="2">Item 9A.</td>
<td>Controls and Procedures</td>
<td>99</td>
</tr>
<tr>
<td colspan="2"></td>
<td>Report of Management on Internal Control over Financial Reporting</td>
<td>99</td>
</tr>
<tr>
<td colspan="2"></td>
<td>Report of Independent Registered Public Accounting Firm</td>
<td>100</td>
</tr>
<tr>
<td></td>
<td>Item 9B.</td>
<td>Other Information</td>
<td>101</td>
</tr>
<tr>
<td></td>
<td>Item 9C.</td>
<td>Disclosure Regarding Foreign Jurisdictions that Prevent Inspections</td>
<td>101</td>
</tr>
<tr>
<td colspan="2">PART III</td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td>Item 10.</td>
<td>Directors, Executive Officers, and Corporate Governance</td>
<td>101</td>
</tr>
<tr>
<td colspan="2">Item 11.</td>
<td>Executive Compensation</td>
<td>101</td>
</tr>
<tr>
<td colspan="2">Item 12.</td>
<td>Security Ownership of Certain Beneficial Owners and Management and Related Stockholder Matters</td>
<td>101</td>
</tr>
<tr>
<td colspan="2">Item 13.</td>
<td>Certain Relationships and Related Transactions, and Director Independence</td>
<td>101</td>
</tr>
<tr>
<td></td>
<td>Item 14.</td>
<td>Principal Accountant Fees and Services</td>
<td>101</td>
</tr>
<tr>
<td colspan="2">PART IV</td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td>Item 15.</td>
<td>Exhibit and Financial Statement Schedules</td>
<td>102</td>
</tr>
<tr>
<td></td>
<td>Item 16.</td>
<td>Form 10-K Summary</td>
<td>108</td>
</tr>
<tr>
<td></td>
<td></td>
<td>Signatures</td>
<td>109</td>
</tr>
</table>


<!-- PageNumber="2" -->
<!-- PageBreak -->


# PARTI Item 1


## Note About Forward-Looking Statements

This report includes estimates, projections, statements relating to our business plans, objectives, and expected operating results that are "forward-looking
statements" within the meaning of the Private Securities Litigation Reform Act of 1995, Section 27A of the Securities Act of 1933, and Section 21E of the
Securities Exchange Act of 1934. Forward-looking statements may appear throughout this report, including the following sections: "Business" (Part I, Item
1 of this Form 10-K), "Risk Factors" (Part I, Item 1A of this Form 10-K), and "Management's Discussion and Analysis of Financial Condition and Results of
Operations" (Part II, Item 7 of this Form 10-K). These forward-looking statements generally are identified by the words "believe," "project," "expect,"
"anticipate," "estimate," "intend," "strategy," "future," "opportunity," "plan," "may," "should," "will," "would," "will be," "will continue," "will likely result," and
similar expressions. Forward-looking statements are based on current expectations and assumptions that are subject to risks and uncertainties that may
cause actual results to differ materially. We describe risks and uncertainties that could cause actual results and events to differ materially in "Risk
Factors," "Management's Discussion and Analysis of Financial Condition and Results of Operations," and "Quantitative and Qualitative Disclosures about
Market Risk" (Part II, Item 7A of this Form 10-K). Readers are cautioned not to place undue reliance on forward-looking statements, which speak only as
of the date they are made. We undertake no obligation to update or revise publicly any forward-looking statements, whether because of new information,
future events, or otherwise.

<!-- PageNumber="3" -->
<!-- PageBreak -->

<!-- PageHeader="PARTI Item 1" -->


# PART I


## ITEM 1. BUSINESS

GENERAL


### Embracing Our Future

Microsoft is a technology company whose mission is to empower every person and every organization on the planet to achieve more. We strive to create
local opportunity, growth, and impact in every country around the world. We are creating the platforms and tools, powered by artificial intelligence ("AI"),
that deliver better, faster, and more effective solutions to support small and large business competitiveness, improve educational and health outcomes,
grow public-sector efficiency, and empower human ingenuity. From infrastructure and data, to business applications and collaboration, we provide
unique, differentiated value to customers.

In a world of increasing economic complexity, AI has the power to revolutionize many types of work. Microsoft is now innovating and expanding our
portfolio with Al capabilities to help people and organizations overcome today's challenges and emerge stronger. Customers are looking to unlock value
from their digital spend and innovate for this next generation of AI, while simplifying security and management. Those leveraging the Microsoft Cloud are
best positioned to take advantage of technological advancements and drive innovation. Our investment in Al spans the entire company, from Microsoft
Teams and Outlook, to Bing and Xbox, and we are infusing generative Al capability into our consumer and commercial offerings to deliver copilot
capability for all services across the Microsoft Cloud.

We're committed to making the promise of Al real - and doing it responsibly. Our work is guided by a core set of principles: fairness, reliability and safety,
privacy and security, inclusiveness, transparency, and accountability.


### What We Offer

Founded in 1975, we develop and support software, services, devices, and solutions that deliver new value for customers and help people and
businesses realize their full potential.

We offer an array of services, including cloud-based solutions that provide customers with software, services, platforms, and content, and we provide
solution support and consulting services. We also deliver relevant online advertising to a global audience.

Our products include operating systems, cross-device productivity and collaboration applications, server applications, business solution applications,
desktop and server management tools, software development tools, and video games. We also design and sell devices, including PCs, tablets, gaming
and entertainment consoles, other intelligent devices, and related accessories.


### The Ambitions That Drive Us

To achieve our vision, our research and development efforts focus on three interconnected ambitions:

·Reinvent productivity and business processes.

·Build the intelligent cloud and intelligent edge platform.

·Create more personal computing.


### Reinvent Productivity and Business Processes

At Microsoft, we provide technology and resources to help our customers create a secure, productive work environment. Our family of products plays a
key role in the ways the world works, learns, and connects.

<!-- PageNumber="4" -->
<!-- PageBreak -->

<!-- PageHeader="PART I" -->
<!-- PageNumber="Item 1" -->

Our growth depends on securely delivering continuous innovation and advancing our leading productivity and collaboration tools and services, including
Office 365, Dynamics 365, and LinkedIn. Microsoft 365 brings together Office 365, Windows, and Enterprise Mobility + Security to help organizations
empower their employees with AI-backed tools that unlock creativity, increase collaboration, and fuel innovation, all the while enabling compliance
coverage and data protection. Microsoft Teams is a comprehensive platform for work, with meetings, calls, chat, collaboration, and business process
automation. Microsoft Viva is an employee experience platform that brings together communications, knowledge, learning, resources, and insights.
Microsoft 365 Copilot combines next-generation Al with business data in the Microsoft Graph and Microsoft 365 applications.

Together with the Microsoft Cloud, Dynamics 365, Microsoft Teams, and our AI offerings bring a new era of collaborative applications that optimize
business functions, processes, and applications to better serve customers and employees while creating more business value. Microsoft Power Platform
is helping domain experts drive productivity gains with low-code/no-code tools, robotic process automation, virtual agents, and business intelligence. In a
dynamic labor market, LinkedIn is helping professionals use the platform to connect, learn, grow, and get hired.


### Build the Intelligent Cloud and Intelligent Edge Platform

As digital transformation and adoption of AI accelerates and revolutionizes more business workstreams, organizations in every sector across the globe
can address challenges that will have a fundamental impact on their success. For enterprises, digital technology empowers employees, optimizes
operations, engages customers, and in some cases, changes the very core of products and services. We continue to invest in high performance and
sustainable computing to meet the growing demand for fast access to Microsoft services provided by our network of cloud computing infrastructure and
datacenters.

Our cloud business benefits from three economies of scale: datacenters that deploy computational resources at significantly lower cost per unit than
smaller ones; datacenters that coordinate and aggregate diverse customer, geographic, and application demand patterns, improving the utilization of
computing, storage, and network resources; and multi-tenancy locations that lower application maintenance labor costs.

The Microsoft Cloud provides the best integration across the technology stack while offering openness, improving time to value, reducing costs, and
increasing agility. Being a global-scale cloud, Azure uniquely offers hybrid consistency, developer productivity, Al capabilities, and trusted security and
compliance. We see more emerging use cases and needs for compute and security at the edge and are accelerating our innovation across the spectrum
of intelligent edge devices, from Internet of Things ("loT") sensors to gateway devices and edge hardware to build, manage, and secure edge workloads.

Our AI platform, Azure AI, is helping organizations transform, bringing intelligence and insights to the hands of their employees and customers to solve
their most pressing challenges. Organizations large and small are deploying Azure Al solutions to achieve more at scale, more easily, with the proper
enterprise-level and responsible AI protections.

We have a long-term partnership with OpenAI, a leading Al research and deployment company. We deploy OpenAl's models across our consumer and
enterprise products. As OpenAl's exclusive cloud provider, Azure powers all of OpenAl's workloads. We have also increased our investments in the
development and deployment of specialized supercomputing systems to accelerate OpenAl's research.

Our hybrid infrastructure offers integrated, end-to-end security, compliance, identity, and management capabilities to support the real-world needs and
evolving regulatory requirements of commercial customers and enterprises. Our industry clouds bring together capabilities across the entire Microsoft
Cloud, along with industry-specific customizations. Azure Arc simplifies governance and management by delivering a consistent multi-cloud and on-
premises management platform.

Nuance, a leader in conversational AI and ambient intelligence across industries including healthcare, financial services, retail, and telecommunications,
joined Microsoft in 2022. Microsoft and Nuance enable organizations to accelerate their business goals with security-focused, cloud-based solutions
infused with AI.

We are accelerating our development of mixed reality solutions with new Azure services and devices. Microsoft Mesh enables organizations to create
custom, immersive experiences for the workplace to help bring remote and hybrid workers and teams together.

<!-- PageNumber="5" -->
<!-- PageBreak -->

<!-- PageHeader="PART I" -->
<!-- PageNumber="Item 1" -->

The ability to convert data into AI drives our competitive advantage. The Microsoft Intelligent Data Platform is a leading cloud data platform that fully
integrates databases, analytics, and governance. The platform empowers organizations to invest more time creating value rather than integrating and
managing their data. Microsoft Fabric is an end-to-end, unified analytics platform that brings together all the data and analytics tools that organizations
need.

GitHub Copilot is at the forefront of AI-powered software development, giving developers a new tool to write code easier and faster so they can focus on
more creative problem-solving. From GitHub to Visual Studio, we provide a developer tool chain for everyone, no matter the technical experience, across
all platforms, whether Azure, Windows, or any other cloud or client platform.

Windows also plays a critical role in fueling our cloud business with Windows 365, a desktop operating system that's also a cloud service. From another
internet-connected device, including Android or macOS devices, users can run Windows 365, just like a virtual machine.

Additionally, we are extending our infrastructure beyond the planet, bringing cloud computing to space. Azure Orbital is a fully managed ground station
as a service for fast downlinking of data.


### Create More Personal Computing

We strive to make computing more personal, enabling users to interact with technology in more intuitive, engaging, and dynamic ways.

Windows 11 offers innovations focused on enhancing productivity, including Windows Copilot with centralized AI assistance and Dev Home to help
developers become more productive. Windows 11 security and privacy features include operating system security, application security, and user and
identity security.

Through our Search, News, Mapping, and Browser services, Microsoft delivers unique trust, privacy, and safety features. In February 2023, we launched
an all new, Al-powered Microsoft Edge browser and Bing search engine with Bing Chat to deliver better search, more complete answers, and the ability
to generate content. Microsoft Edge is our fast and secure browser that helps protect users' data. Quick access to Al-powered tools, apps, and more
within Microsoft Edge's sidebar enhance browsing capabilities.


### Formatting output

In [35]:
def MdFormatting(ocr_extraction):
    doc_string = ocr_extraction.content
    ## Split the document into chunks base on markdown headers.
    headers_to_split_on = [
        ("#", "Title"),
        ("##", "Header 1"),
        ("###", "Header 2"),
    ]
    text_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on)

    markdown_chunks = text_splitter.split_text(doc_string)

    chunk_list = []
    for chunk in markdown_chunks:
        try:
            title = chunk.metadata['Title']
        except:
            title = ""
        try:
            header1 = chunk.metadata['Header 1']
        except:
            header1 = ""
        try:
            header2 = chunk.metadata['Header 2']
        except:
            header2 = ""

        chunk_list.append({"title": title,"header_1":header1,"header_2":header2,"content": title + "/n" + header1 + "/n"+ chunk.page_content})
    return pd.DataFrame(chunk_list)

In [37]:
output_df = MdFormatting(Extracted_data)

In [47]:
pd.set_option('display.max_rows', 500)

In [52]:
output_df[output_df['header_2']!=""]

,title,header_1,header_2,content
6,PART I,ITEM 1. BUSINESS,Embracing Our Future,PART I/nITEM 1. BUSINESS/nMicrosoft is a techn...
7,PART I,ITEM 1. BUSINESS,What We Offer,"PART I/nITEM 1. BUSINESS/nFounded in 1975, we ..."
8,PART I,ITEM 1. BUSINESS,The Ambitions That Drive Us,PART I/nITEM 1. BUSINESS/nTo achieve our visio...
9,PART I,ITEM 1. BUSINESS,Reinvent Productivity and Business Processes,"PART I/nITEM 1. BUSINESS/nAt Microsoft, we pro..."
10,PART I,ITEM 1. BUSINESS,Build the Intelligent Cloud and Intelligent Ed...,PART I/nITEM 1. BUSINESS/nAs digital transform...
11,PART I,ITEM 1. BUSINESS,Create More Personal Computing,PART I/nITEM 1. BUSINESS/nWe strive to make co...
12,PART I,ITEM 1. BUSINESS,Our Future Opportunity,PART I/nITEM 1. BUSINESS/nWe are focused on he...
13,PART I,ITEM 1. BUSINESS,Corporate Social Responsibility,PART I/nITEM 1. BUSINESS/n#### Commitment to S...
14,PART I,ITEM 1. BUSINESS,HUMAN CAPITAL RESOURCES,PART I/nITEM 1. BUSINESS/n#### Overview \nMic...
21,OPERATING SEGMENTS,Dynamics,Competition,OPERATING SEGMENTS/nDynamics/nCompetitors to O...
22,OPERATING SEGMENTS,Dynamics,Intelligent Cloud,OPERATING SEGMENTS/nDynamics/nOur Intelligent ...
23,OPERATING SEGMENTS,Dynamics,Server Products and Cloud Services,OPERATING SEGMENTS/nDynamics/nAzure is a compr...
24,OPERATING SEGMENTS,Dynamics,Enterprise Services,OPERATING SEGMENTS/nDynamics/nEnterprise Servi...
25,OPERATING SEGMENTS,Dynamics,More Personal Computing,OPERATING SEGMENTS/nDynamics/nOur More Persona...
26,OPERATING SEGMENTS,Dynamics,Windows,OPERATING SEGMENTS/nDynamics/nThe Windows oper...
27,OPERATING SEGMENTS,Dynamics,Devices,OPERATING SEGMENTS/nDynamics/nWe design and se...
28,OPERATING SEGMENTS,Dynamics,Gaming,OPERATING SEGMENTS/nDynamics/nOur gaming platf...
29,OPERATING SEGMENTS,Dynamics,Search and News Advertising,OPERATING SEGMENTS/nDynamics/nOur Search and n...
30,OPERATING SEGMENTS,Dynamics,Competition,OPERATING SEGMENTS/nDynamics/nWindows faces co...
39,LICENSING OPTIONS,Volume Licensing Programs,Enterprise Agreement,LICENSING OPTIONS/nVolume Licensing Programs/n...
40,LICENSING OPTIONS,Volume Licensing Programs,Microsoft Customer Agreement,LICENSING OPTIONS/nVolume Licensing Programs/n...
41,LICENSING OPTIONS,Volume Licensing Programs,Microsoft Online Subscription Agreement,LICENSING OPTIONS/nVolume Licensing Programs/n...
42,LICENSING OPTIONS,Volume Licensing Programs,Microsoft Products and Services Agreement,LICENSING OPTIONS/nVolume Licensing Programs/n...
43,LICENSING OPTIONS,Volume Licensing Programs,Open Value,LICENSING OPTIONS/nVolume Licensing Programs/n...
44,LICENSING OPTIONS,Volume Licensing Programs,Select Plus,LICENSING OPTIONS/nVolume Licensing Programs/n...
45,LICENSING OPTIONS,Volume Licensing Programs,Partner Programs,LICENSING OPTIONS/nVolume Licensing Programs/n...
51,AVAILABLE INFORMATION,ITEM 1A. RISK FACTORS,STRATEGIC AND COMPETITIVE RISKS,AVAILABLE INFORMATION/nITEM 1A. RISK FACTORS/n...
54,PART I Item 1A,"CYBERSECURITY, DATA PRIVACY, AND PLATFORM ABUS...",Cyberattacks and security vulnerabilities coul...,"PART I Item 1A/nCYBERSECURITY, DATA PRIVACY, A..."
55,PART I Item 1A,"CYBERSECURITY, DATA PRIVACY, AND PLATFORM ABUS...",Abuse of our platforms may harm our reputation...,"PART I Item 1A/nCYBERSECURITY, DATA PRIVACY, A..."
67,PART I Item 1A,ITEM 4. MINE SAFETY DISCLOSURES,PART II,PART I Item 1A/nITEM 4. MINE SAFETY DISCLOSURE...
69,PART II Item 7,Reportable Segments,Metrics,PART II Item 7/nReportable Segments/nWe use me...
70,PART II Item 7,Reportable Segments,Commercial,PART II Item 7/nReportable Segments/nOur comme...
74,SEGMENT RESULTS OF OPERATIONS,Reportable Segments,Fiscal Year 2023 Compared with Fiscal Year 2022,SEGMENT RESULTS OF OPERATIONS/nReportable Segm...
75,SEGMENT RESULTS OF OPERATIONS,Reportable Segments,More Personal Computing,SEGMENT RESULTS OF OPERATIONS/nReportable Segm...
76,PART II Item 7,OPERATING EXPENSES,Research and Development,PART II Item 7/nOPERATING EXPENSES/n<table>\n<...
77,PART II Item 7,OPERATING EXPENSES,General and Administrative,PART II Item 7/nOPERATING EXPENSES/n<table>\n<...
79,PART II Item 7,"OTHER INCOME (EXPENSE), NET",(In millions),"PART II Item 7/nOTHER INCOME (EXPENSE), NET/n<..."
89,LIQUIDITY AND CAPITAL RESOURCES,Unearned Revenue,Three Months Ending,LIQUIDITY AND CAPITAL RESOURCES/nUnearned Reve...
90,LIQUIDITY AND CAPITAL RESOURCES,Material Cash Requirements and Other Obligations,Contractual Obligations,LIQUIDITY AND CAPITAL RESOURCES/nMaterial Cash...
91,LIQUIDITY AND CAPITAL RESOURCES,Material Cash Requirements and Other Obligations,Income Taxes,LIQUIDITY AND CAPITAL RESOURCES/nMaterial Cash...
92,LIQUIDITY AND CAPITAL RESOURCES,Material Cash Requirements and Other Obligations,Share Repurchases,LIQUIDITY AND CAPITAL RESOURCES/nMaterial Cash...
93,LIQUIDITY AND CAPITAL RESOURCES,Material Cash Requirements and Other Obligations,Dividends,LIQUIDITY AND CAPITAL RESOURCES/nMaterial Cash...
94,LIQUIDITY AND CAPITAL RESOURCES,Material Cash Requirements and Other Obligations,Other Planned Uses of Capital,LIQUIDITY AND CAPITAL RESOURCES/nMaterial Cash...
104,PART II Item 7A,ITEM 7A. QUANTITATIVE AND QUALITATIVE DISCLOSU...,RISKS,PART II Item 7A/nITEM 7A. QUANTITATIVE AND QUA...
105,PART II Item 7A,ITEM 7A. QUANTITATIVE AND QUALITATIVE DISCLOSU...,SENSITIVITY ANALYSIS,PART II Item 7A/nITEM 7A. QUANTITATIVE AND QUA...
110,CASH FLOWS STATEMENTS,STOCKHOLDERS' EQUITY STATEMENTS,"(In millions, except per share amounts)",CASH FLOWS STATEMENTS/nSTOCKHOLDERS' EQUITY ST...
111,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Accounting Principles,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
112,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Principles of Consolidation,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
113,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Estimates and Assumptions,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
114,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Foreign Currencies,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
115,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Revenue,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
116,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Financial Instruments,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
117,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Fair Value Measurements,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
118,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Inventories,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
119,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Property and Equipment,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
120,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Leases,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
121,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Goodwill,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
122,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Intangible Assets,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
124,PART II Item 8,NOTE 2 - EARNINGS PER SHARE,"NOTE 3 - OTHER INCOME (EXPENSE), NET",PART II Item 8/nNOTE 2 - EARNINGS PER SHARE/nT...
125,PART II Item 8,NOTE 2 - EARNINGS PER SHARE,NOTE 4 - INVESTMENTS,PART II Item 8/nNOTE 2 - EARNINGS PER SHARE/n#...
127,PART II Item 8,NOTE 5 - DERIVATIVES,Foreign Currencies,PART II Item 8/nNOTE 5 - DERIVATIVES/nCertain ...
128,PART II Item 8,NOTE 5 - DERIVATIVES,Interest Rate,PART II Item 8/nNOTE 5 - DERIVATIVES/nInterest...
129,PART II Item 8,NOTE 5 - DERIVATIVES,Equity,PART II Item 8/nNOTE 5 - DERIVATIVES/nSecuriti...
130,PART II Item 8,NOTE 5 - DERIVATIVES,Credit,PART II Item 8/nNOTE 5 - DERIVATIVES/nOur fixe...
131,PART II Item 8,NOTE 5 - DERIVATIVES,Credit-Risk-Related Contingent Features,PART II Item 8/nNOTE 5 - DERIVATIVES/nCertain ...
132,PART II Item 8,NOTE 5 - DERIVATIVES,Fair Values of Derivative Instruments,PART II Item 8/nNOTE 5 - DERIVATIVES/nThe foll...
133,PART II Item 8,NOTE 5 - DERIVATIVES,(In millions),PART II Item 8/nNOTE 5 - DERIVATIVES/n<table>\...
136,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,NOTE 8 - BUSINESS COMBINATIONS,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
137,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,NOTE 9 - GOODWILL,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
138,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,NOTE 10 - INTANGIBLE ASSETS,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
139,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,NOTE 11 - DEBT,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
140,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,NOTE 12 - INCOME TAXES,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
141,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,U.S. and foreign components of income before i...,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
142,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,Effective Tax Rate,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
144,PART II Item 8,NOTE 13 - UNEARNED REVENUE,(In millions),PART II Item 8/nNOTE 13 - UNEARNED REVENUE/n<t...
146,PART II Item 8,NOTE 14 - LEASES,"(In millions, except lease term and discount r...",PART II Item 8/nNOTE 14 - LEASES/n<table>\n<tr...
147,PART II Item 8,NOTE 15 - CONTINGENCIES,U.S. Cell Phone Litigation,PART II Item 8/nNOTE 15 - CONTINGENCIES/nMicro...
148,PART II Item 8,NOTE 15 - CONTINGENCIES,Irish Data Protection Commission Matter,PART II Item 8/nNOTE 15 - CONTINGENCIES/nIn 20...
149,PART II Item 8,NOTE 15 - CONTINGENCIES,Other Contingencies,PART II Item 8/nNOTE 15 - CONTINGENCIES/nWe al...
150,PART II Item 8,NOTE 16 - STOCKHOLDERS' EQUITY,Shares Outstanding,PART II Item 8/nNOTE 16 - STOCKHOLDERS' EQUITY...
151,PART II Item 8,NOTE 16 - STOCKHOLDERS' EQUITY,Share Repurchases,PART II Item 8/nNOTE 16 - STOCKHOLDERS' EQUITY...
154,PART II Item 8,Dividends,NOTE 17 - ACCUMULATED OTHER COMPREHENSIVE INCO...,PART II Item 8/nDividends/nThe following table...
155,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,To the Stockholders and the Board of Directors...,Opinion on the Financial Statements,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...
156,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,To the Stockholders and the Board of Directors...,Basis for Opinion,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...
157,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,To the Stockholders and the Board of Directors...,Critical Audit Matters,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...
158,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,To the Stockholders and the Board of Directors...,Revenue Recognition - Refer to Note 1 to the f...,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...
159,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,Income Taxes - Uncertain Tax Positions - Refer...,Critical Audit Matter Description,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...
164,ITEM 9A. CONTROLS AND PROCEDURES,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,To the Stockholders and the Board of Directors...,ITEM 9A. CONTROLS AND PROCEDURES/nREPORT OF IN...
172,PART IV,ITEM 15. EXHIBIT AND FINANCIAL STATEMENT SCHED...,(a)Financial Statements and Schedules,PART IV/nITEM 15. EXHIBIT AND FINANCIAL STATEM...
173,PART IV,ITEM 15. EXHIBIT AND FINANCIAL STATEMENT SCHED...,(b)Exhibit Listing,PART IV/nITEM 15. EXHIBIT AND FINANCIAL STATEM...
176,PART IV Item 16,ITEM 16. FORM 10-K SUMMARY,SIGNATURES,PART IV Item 16/nITEM 16. FORM 10-K SUMMARY/nP...

In [53]:
output_df

,title,header_1,header_2,content
0,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...,,,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...
1,MICROSOFT CORPORATION,,,MICROSOFT CORPORATION/n/n<table>\n<tr>\n<th>WA...
2,MICROSOFT CORPORATION,DOCUMENTS INCORPORATED BY REFERENCE,,MICROSOFT CORPORATION/nDOCUMENTS INCORPORATED ...
3,MICROSOFT CORPORATION,MICROSOFT CORPORATION FORM 10-K For the Fiscal...,,MICROSOFT CORPORATION/nMICROSOFT CORPORATION F...
4,PARTI Item 1,Note About Forward-Looking Statements,,PARTI Item 1/nNote About Forward-Looking State...
5,PART I,ITEM 1. BUSINESS,,PART I/nITEM 1. BUSINESS/nGENERAL
6,PART I,ITEM 1. BUSINESS,Embracing Our Future,PART I/nITEM 1. BUSINESS/nMicrosoft is a techn...
7,PART I,ITEM 1. BUSINESS,What We Offer,"PART I/nITEM 1. BUSINESS/nFounded in 1975, we ..."
8,PART I,ITEM 1. BUSINESS,The Ambitions That Drive Us,PART I/nITEM 1. BUSINESS/nTo achieve our visio...
9,PART I,ITEM 1. BUSINESS,Reinvent Productivity and Business Processes,"PART I/nITEM 1. BUSINESS/nAt Microsoft, we pro..."
10,PART I,ITEM 1. BUSINESS,Build the Intelligent Cloud and Intelligent Ed...,PART I/nITEM 1. BUSINESS/nAs digital transform...
11,PART I,ITEM 1. BUSINESS,Create More Personal Computing,PART I/nITEM 1. BUSINESS/nWe strive to make co...
12,PART I,ITEM 1. BUSINESS,Our Future Opportunity,PART I/nITEM 1. BUSINESS/nWe are focused on he...
13,PART I,ITEM 1. BUSINESS,Corporate Social Responsibility,PART I/nITEM 1. BUSINESS/n#### Commitment to S...
14,PART I,ITEM 1. BUSINESS,HUMAN CAPITAL RESOURCES,PART I/nITEM 1. BUSINESS/n#### Overview \nMic...
15,OPERATING SEGMENTS,,,OPERATING SEGMENTS/n/nWe operate our business ...
16,OPERATING SEGMENTS,Productivity and Business Processes,,OPERATING SEGMENTS/nProductivity and Business ...
17,OPERATING SEGMENTS,Office Commercial,,OPERATING SEGMENTS/nOffice Commercial/nOffice ...
18,OPERATING SEGMENTS,Office Consumer,,OPERATING SEGMENTS/nOffice Consumer/nOffice Co...
19,OPERATING SEGMENTS,Linkedin,,OPERATING SEGMENTS/nLinkedin/nLinkedIn connect...
20,OPERATING SEGMENTS,Dynamics,,OPERATING SEGMENTS/nDynamics/nDynamics provide...
21,OPERATING SEGMENTS,Dynamics,Competition,OPERATING SEGMENTS/nDynamics/nCompetitors to O...
22,OPERATING SEGMENTS,Dynamics,Intelligent Cloud,OPERATING SEGMENTS/nDynamics/nOur Intelligent ...
23,OPERATING SEGMENTS,Dynamics,Server Products and Cloud Services,OPERATING SEGMENTS/nDynamics/nAzure is a compr...
24,OPERATING SEGMENTS,Dynamics,Enterprise Services,OPERATING SEGMENTS/nDynamics/nEnterprise Servi...
25,OPERATING SEGMENTS,Dynamics,More Personal Computing,OPERATING SEGMENTS/nDynamics/nOur More Persona...
26,OPERATING SEGMENTS,Dynamics,Windows,OPERATING SEGMENTS/nDynamics/nThe Windows oper...
27,OPERATING SEGMENTS,Dynamics,Devices,OPERATING SEGMENTS/nDynamics/nWe design and se...
28,OPERATING SEGMENTS,Dynamics,Gaming,OPERATING SEGMENTS/nDynamics/nOur gaming platf...
29,OPERATING SEGMENTS,Dynamics,Search and News Advertising,OPERATING SEGMENTS/nDynamics/nOur Search and n...
30,OPERATING SEGMENTS,Dynamics,Competition,OPERATING SEGMENTS/nDynamics/nWindows faces co...
31,OPERATIONS,,,OPERATIONS/n/nWe have regional operations serv...
32,RESEARCH AND DEVELOPMENT,"Product and Service Development, and Intellect...",,RESEARCH AND DEVELOPMENT/nProduct and Service ...
33,RESEARCH AND DEVELOPMENT,Investing in the Future,,RESEARCH AND DEVELOPMENT/nInvesting in the Fut...
34,"DISTRIBUTION, SALES, AND MARKETING",,,"DISTRIBUTION, SALES, AND MARKETING/n/nWe marke..."
35,"DISTRIBUTION, SALES, AND MARKETING",OEMs,,"DISTRIBUTION, SALES, AND MARKETING/nOEMs/nWe d..."
36,"DISTRIBUTION, SALES, AND MARKETING",Direct,,"DISTRIBUTION, SALES, AND MARKETING/nDirect/nMa..."
37,"DISTRIBUTION, SALES, AND MARKETING",Distributors and Resellers,,"DISTRIBUTION, SALES, AND MARKETING/nDistributo..."
38,LICENSING OPTIONS,,,LICENSING OPTIONS/n/nWe offer options for orga...
39,LICENSING OPTIONS,Volume Licensing Programs,Enterprise Agreement,LICENSING OPTIONS/nVolume Licensing Programs/n...
40,LICENSING OPTIONS,Volume Licensing Programs,Microsoft Customer Agreement,LICENSING OPTIONS/nVolume Licensing Programs/n...
41,LICENSING OPTIONS,Volume Licensing Programs,Microsoft Online Subscription Agreement,LICENSING OPTIONS/nVolume Licensing Programs/n...
42,LICENSING OPTIONS,Volume Licensing Programs,Microsoft Products and Services Agreement,LICENSING OPTIONS/nVolume Licensing Programs/n...
43,LICENSING OPTIONS,Volume Licensing Programs,Open Value,LICENSING OPTIONS/nVolume Licensing Programs/n...
44,LICENSING OPTIONS,Volume Licensing Programs,Select Plus,LICENSING OPTIONS/nVolume Licensing Programs/n...
45,LICENSING OPTIONS,Volume Licensing Programs,Partner Programs,LICENSING OPTIONS/nVolume Licensing Programs/n...
46,CUSTOMERS,,,CUSTOMERS/n/nOur customers include individual ...
47,INFORMATION ABOUT OUR EXECUTIVE OFFICERS,,,INFORMATION ABOUT OUR EXECUTIVE OFFICERS/n/nOu...
48,PART I Item 1,,,PART I Item 1/n/nMr. Capossela was appointed E...
49,AVAILABLE INFORMATION,,,AVAILABLE INFORMATION/n/nOur Internet address ...
50,AVAILABLE INFORMATION,ITEM 1A. RISK FACTORS,,AVAILABLE INFORMATION/nITEM 1A. RISK FACTORS/n...
51,AVAILABLE INFORMATION,ITEM 1A. RISK FACTORS,STRATEGIC AND COMPETITIVE RISKS,AVAILABLE INFORMATION/nITEM 1A. RISK FACTORS/n...
52,PART I Item 1A,,,PART I Item 1A/n/nIt is uncertain whether our ...
53,PART I Item 1A,RISKS RELATING TO THE EVOLUTION OF OUR BUSINESS,,PART I Item 1A/nRISKS RELATING TO THE EVOLUTIO...
54,PART I Item 1A,"CYBERSECURITY, DATA PRIVACY, AND PLATFORM ABUS...",Cyberattacks and security vulnerabilities coul...,"PART I Item 1A/nCYBERSECURITY, DATA PRIVACY, A..."
55,PART I Item 1A,"CYBERSECURITY, DATA PRIVACY, AND PLATFORM ABUS...",Abuse of our platforms may harm our reputation...,"PART I Item 1A/nCYBERSECURITY, DATA PRIVACY, A..."
56,PART I Item 1A,OPERATIONAL RISKS,,PART I Item 1A/nOPERATIONAL RISKS/nWe may have...
57,PART I Item 1A,"LEGAL, REGULATORY, AND LITIGATION RISKS",,"PART I Item 1A/nLEGAL, REGULATORY, AND LITIGAT..."
58,PART I Item 1A,,,"PART I Item 1A/n/nFor example, the European Co..."
59,INTELLECTUAL PROPERTY RISKS,,,INTELLECTUAL PROPERTY RISKS/n/nWe face risks r...
60,GENERAL RISKS,,,GENERAL RISKS/n/nIf our reputation or our bran...
61,PARTI Item 1A,,,PARTI Item 1A/n/nWe maintain an investment por...
62,PART I Item 1A,,,PART I Item 1A/n/nOur global business exposes ...
63,PART I Item 1A,ITEM 1B. UNRESOLVED STAFF COMMENTS,,PART I Item 1A/nITEM 1B. UNRESOLVED STAFF COMM...
64,PART I Item 1A,ITEM 2. PROPERTIES,,PART I Item 1A/nITEM 2. PROPERTIES/nOur corpor...
65,PART I Item 1A,ITEM 3. LEGAL PROCEEDINGS,,PART I Item 1A/nITEM 3. LEGAL PROCEEDINGS/nRef...
66,PART I Item 1A,ITEM 4. MINE SAFETY DISCLOSURES,,PART I Item 1A/nITEM 4. MINE SAFETY DISCLOSURE...
67,PART I Item 1A,ITEM 4. MINE SAFETY DISCLOSURES,PART II,PART I Item 1A/nITEM 4. MINE SAFETY DISCLOSURE...
68,PART II Item 7,Reportable Segments,,PART II Item 7/nReportable Segments/nWe report...
69,PART II Item 7,Reportable Segments,Metrics,PART II Item 7/nReportable Segments/nWe use me...
70,PART II Item 7,Reportable Segments,Commercial,PART II Item 7/nReportable Segments/nOur comme...
71,SUMMARY RESULTS OF OPERATIONS,,,SUMMARY RESULTS OF OPERATIONS/n/n<table>\n<tr>...
72,SUMMARY RESULTS OF OPERATIONS,Fiscal Year 2023 Compared with Fiscal Year 2022,,SUMMARY RESULTS OF OPERATIONS/nFiscal Year 202...
73,SEGMENT RESULTS OF OPERATIONS,,,SEGMENT RESULTS OF OPERATIONS/n/n<table>\n<tr>...
74,SEGMENT RESULTS OF OPERATIONS,Reportable Segments,Fiscal Year 2023 Compared with Fiscal Year 2022,SEGMENT RESULTS OF OPERATIONS/nReportable Segm...
75,SEGMENT RESULTS OF OPERATIONS,Reportable Segments,More Personal Computing,SEGMENT RESULTS OF OPERATIONS/nReportable Segm...
76,PART II Item 7,OPERATING EXPENSES,Research and Development,PART II Item 7/nOPERATING EXPENSES/n<table>\n<...
77,PART II Item 7,OPERATING EXPENSES,General and Administrative,PART II Item 7/nOPERATING EXPENSES/n<table>\n<...
78,PART II Item 7,"OTHER INCOME (EXPENSE), NET",,"PART II Item 7/nOTHER INCOME (EXPENSE), NET/nT..."
79,PART II Item 7,"OTHER INCOME (EXPENSE), NET",(In millions),"PART II Item 7/nOTHER INCOME (EXPENSE), NET/n<..."
80,INCOME TAXES,Effective Tax Rate,,INCOME TAXES/nEffective Tax Rate/nOur effectiv...
81,INCOME TAXES,Uncertain Tax Positions,,INCOME TAXES/nUncertain Tax Positions/nWe sett...
82,NON-GAAP FINANCIAL MEASURES,,,NON-GAAP FINANCIAL MEASURES/n/nAdjusted gross ...
83,LIQUIDITY AND CAPITAL RESOURCES,,,LIQUIDITY AND CAPITAL RESOURCES/n/nWe expect e...
84,LIQUIDITY AND CAPITAL RESOURCES,"Cash, Cash Equivalents, and Investments",,"LIQUIDITY AND CAPITAL RESOURCES/nCash, Cash Eq..."
85,LIQUIDITY AND CAPITAL RESOURCES,Valuation,,LIQUIDITY AND CAPITAL RESOURCES/nValuation/nIn...
86,LIQUIDITY AND CAPITAL RESOURCES,Cash Flows,,LIQUIDITY AND CAPITAL RESOURCES/nCash Flows/nC...
87,LIQUIDITY AND CAPITAL RESOURCES,Debt Proceeds,,LIQUIDITY AND CAPITAL RESOURCES/nDebt Proceeds...
88,LIQUIDITY AND CAPITAL RESOURCES,Unearned Revenue,,LIQUIDITY AND CAPITAL RESOURCES/nUnearned Reve...
89,LIQUIDITY AND CAPITAL RESOURCES,Unearned Revenue,Three Months Ending,LIQUIDITY AND CAPITAL RESOURCES/nUnearned Reve...
90,LIQUIDITY AND CAPITAL RESOURCES,Material Cash Requirements and Other Obligations,Contractual Obligations,LIQUIDITY AND CAPITAL RESOURCES/nMaterial Cash...
91,LIQUIDITY AND CAPITAL RESOURCES,Material Cash Requirements and Other Obligations,Income Taxes,LIQUIDITY AND CAPITAL RESOURCES/nMaterial Cash...
92,LIQUIDITY AND CAPITAL RESOURCES,Material Cash Requirements and Other Obligations,Share Repurchases,LIQUIDITY AND CAPITAL RESOURCES/nMaterial Cash...
93,LIQUIDITY AND CAPITAL RESOURCES,Material Cash Requirements and Other Obligations,Dividends,LIQUIDITY AND CAPITAL RESOURCES/nMaterial Cash...
94,LIQUIDITY AND CAPITAL RESOURCES,Material Cash Requirements and Other Obligations,Other Planned Uses of Capital,LIQUIDITY AND CAPITAL RESOURCES/nMaterial Cash...
95,CRITICAL ACCOUNTING ESTIMATES,,,CRITICAL ACCOUNTING ESTIMATES/n/nOur consolida...
96,CRITICAL ACCOUNTING ESTIMATES,Revenue Recognition,,CRITICAL ACCOUNTING ESTIMATES/nRevenue Recogni...
97,CRITICAL ACCOUNTING ESTIMATES,Impairment of Investment Securities,,CRITICAL ACCOUNTING ESTIMATES/nImpairment of I...
98,CRITICAL ACCOUNTING ESTIMATES,Goodwill,,CRITICAL ACCOUNTING ESTIMATES/nGoodwill/nWe al...
99,CRITICAL ACCOUNTING ESTIMATES,Research and Development Costs,,CRITICAL ACCOUNTING ESTIMATES/nResearch and De...
100,CRITICAL ACCOUNTING ESTIMATES,Legal and Other Contingencies,,CRITICAL ACCOUNTING ESTIMATES/nLegal and Other...
101,CRITICAL ACCOUNTING ESTIMATES,Income Taxes,,CRITICAL ACCOUNTING ESTIMATES/nIncome Taxes/nT...
102,CRITICAL ACCOUNTING ESTIMATES,Inventories,,CRITICAL ACCOUNTING ESTIMATES/nInventories/nIn...
103,STATEMENT OF MANAGEMENT'S RESPONSIBILITY FOR F...,,,STATEMENT OF MANAGEMENT'S RESPONSIBILITY FOR F...
104,PART II Item 7A,ITEM 7A. QUANTITATIVE AND QUALITATIVE DISCLOSU...,RISKS,PART II Item 7A/nITEM 7A. QUANTITATIVE AND QUA...
105,PART II Item 7A,ITEM 7A. QUANTITATIVE AND QUALITATIVE DISCLOSU...,SENSITIVITY ANALYSIS,PART II Item 7A/nITEM 7A. QUANTITATIVE AND QUA...
106,ITEM 8. FINANCIAL STATEMENTS AND SUPPLEMENTARY...,,,ITEM 8. FINANCIAL STATEMENTS AND SUPPLEMENTARY...
107,ITEM 8. FINANCIAL STATEMENTS AND SUPPLEMENTARY...,COMPREHENSIVE INCOME STATEMENTS,,ITEM 8. FINANCIAL STATEMENTS AND SUPPLEMENTARY...
108,ITEM 8. FINANCIAL STATEMENTS AND SUPPLEMENTARY...,PART II Item 8 BALANCE SHEETS,,ITEM 8. FINANCIAL STATEMENTS AND SUPPLEMENTARY...
109,CASH FLOWS STATEMENTS,,,CASH FLOWS STATEMENTS/n/n(In millions) \n<tab...
110,CASH FLOWS STATEMENTS,STOCKHOLDERS' EQUITY STATEMENTS,"(In millions, except per share amounts)",CASH FLOWS STATEMENTS/nSTOCKHOLDERS' EQUITY ST...
111,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Accounting Principles,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
112,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Principles of Consolidation,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
113,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Estimates and Assumptions,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
114,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Foreign Currencies,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
115,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Revenue,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
116,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Financial Instruments,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
117,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Fair Value Measurements,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
118,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Inventories,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
119,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Property and Equipment,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
120,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Leases,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
121,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Goodwill,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
122,PART II Item 8,NOTES TO FINANCIAL STATEMENTS NOTE 1 - ACCOUNT...,Intangible Assets,PART II Item 8/nNOTES TO FINANCIAL STATEMENTS ...
123,PART II Item 8,NOTE 2 - EARNINGS PER SHARE,,PART II Item 8/nNOTE 2 - EARNINGS PER SHARE/nB...
124,PART II Item 8,NOTE 2 - EARNINGS PER SHARE,"NOTE 3 - OTHER INCOME (EXPENSE), NET",PART II Item 8/nNOTE 2 - EARNINGS PER SHARE/nT...
125,PART II Item 8,NOTE 2 - EARNINGS PER SHARE,NOTE 4 - INVESTMENTS,PART II Item 8/nNOTE 2 - EARNINGS PER SHARE/n#...
126,PART II Item 8,NOTE 5 - DERIVATIVES,,PART II Item 8/nNOTE 5 - DERIVATIVES/nWe use d...
127,PART II Item 8,NOTE 5 - DERIVATIVES,Foreign Currencies,PART II Item 8/nNOTE 5 - DERIVATIVES/nCertain ...
128,PART II Item 8,NOTE 5 - DERIVATIVES,Interest Rate,PART II Item 8/nNOTE 5 - DERIVATIVES/nInterest...
129,PART II Item 8,NOTE 5 - DERIVATIVES,Equity,PART II Item 8/nNOTE 5 - DERIVATIVES/nSecuriti...
130,PART II Item 8,NOTE 5 - DERIVATIVES,Credit,PART II Item 8/nNOTE 5 - DERIVATIVES/nOur fixe...
131,PART II Item 8,NOTE 5 - DERIVATIVES,Credit-Risk-Related Contingent Features,PART II Item 8/nNOTE 5 - DERIVATIVES/nCertain ...
132,PART II Item 8,NOTE 5 - DERIVATIVES,Fair Values of Derivative Instruments,PART II Item 8/nNOTE 5 - DERIVATIVES/nThe foll...
133,PART II Item 8,NOTE 5 - DERIVATIVES,(In millions),PART II Item 8/nNOTE 5 - DERIVATIVES/n<table>\...
134,PART II Item 8,NOTE 6 - INVENTORIES,,PART II Item 8/nNOTE 6 - INVENTORIES/nThe comp...
135,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
136,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,NOTE 8 - BUSINESS COMBINATIONS,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
137,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,NOTE 9 - GOODWILL,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
138,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,NOTE 10 - INTANGIBLE ASSETS,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
139,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,NOTE 11 - DEBT,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
140,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,NOTE 12 - INCOME TAXES,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
141,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,U.S. and foreign components of income before i...,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
142,PART II Item 8,NOTE 7 - PROPERTY AND EQUIPMENT,Effective Tax Rate,PART II Item 8/nNOTE 7 - PROPERTY AND EQUIPMEN...
143,PART II Item 8,NOTE 13 - UNEARNED REVENUE,,PART II Item 8/nNOTE 13 - UNEARNED REVENUE/nUn...
144,PART II Item 8,NOTE 13 - UNEARNED REVENUE,(In millions),PART II Item 8/nNOTE 13 - UNEARNED REVENUE/n<t...
145,PART II Item 8,NOTE 14 - LEASES,,PART II Item 8/nNOTE 14 - LEASES/nWe have oper...
146,PART II Item 8,NOTE 14 - LEASES,"(In millions, except lease term and discount r...",PART II Item 8/nNOTE 14 - LEASES/n<table>\n<tr...
147,PART II Item 8,NOTE 15 - CONTINGENCIES,U.S. Cell Phone Litigation,PART II Item 8/nNOTE 15 - CONTINGENCIES/nMicro...
148,PART II Item 8,NOTE 15 - CONTINGENCIES,Irish Data Protection Commission Matter,PART II Item 8/nNOTE 15 - CONTINGENCIES/nIn 20...
149,PART II Item 8,NOTE 15 - CONTINGENCIES,Other Contingencies,PART II Item 8/nNOTE 15 - CONTINGENCIES/nWe al...
150,PART II Item 8,NOTE 16 - STOCKHOLDERS' EQUITY,Shares Outstanding,PART II Item 8/nNOTE 16 - STOCKHOLDERS' EQUITY...
151,PART II Item 8,NOTE 16 - STOCKHOLDERS' EQUITY,Share Repurchases,PART II Item 8/nNOTE 16 - STOCKHOLDERS' EQUITY...
152,PART II Item 8,,,PART II Item 8/n/nAll repurchases were made us...
153,PART II Item 8,Dividends,,PART II Item 8/nDividends/nOur Board of Direct...
154,PART II Item 8,Dividends,NOTE 17 - ACCUMULATED OTHER COMPREHENSIVE INCO...,PART II Item 8/nDividends/nThe following table...
155,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,To the Stockholders and the Board of Directors...,Opinion on the Financial Statements,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...
156,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,To the Stockholders and the Board of Directors...,Basis for Opinion,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...
157,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,To the Stockholders and the Board of Directors...,Critical Audit Matters,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...
158,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,To the Stockholders and the Board of Directors...,Revenue Recognition - Refer to Note 1 to the f...,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...
159,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,Income Taxes - Uncertain Tax Positions - Refer...,Critical Audit Matter Description,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...
160,PART II Item 8,,,PART II Item 8/n/nHow the Critical Audit Matte...
161,ITEM 9. CHANGES IN AND DISAGREEMENTS WITH ACCO...,,,ITEM 9. CHANGES IN AND DISAGREEMENTS WITH ACCO...
162,ITEM 9A. CONTROLS AND PROCEDURES,,,ITEM 9A. CONTROLS AND PROCEDURES/n/nUnder the ...
163,ITEM 9A. CONTROLS AND PROCEDURES,REPORT OF MANAGEMENT ON INTERNAL CONTROL OVER ...,,ITEM 9A. CONTROLS AND PROCEDURES/nREPORT OF MA...
164,ITEM 9A. CONTROLS AND PROCEDURES,REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUN...,To the Stockholders and the Board of Directors...,ITEM 9A. CONTROLS AND PROCEDURES/nREPORT OF IN...
165,ITEM 9B. OTHER INFORMATION,,,ITEM 9B. OTHER INFORMATION/n/nDuring the three...
166,ITEM 9C. DISCLOSURE REGARDING FOREIGN JURISDIC...,,,ITEM 9C. DISCLOSURE REGARDING FOREIGN JURISDIC...
167,PART III,"ITEM 10. DIRECTORS, EXECUTIVE OFFICERS, AND CO...",,"PART III/nITEM 10. DIRECTORS, EXECUTIVE OFFICE..."
168,PART III,ITEM 11. EXECUTIVE COMPENSATION,,PART III/nITEM 11. EXECUTIVE COMPENSATION/nThe...
169,PART III,ITEM 12. SECURITY OWNERSHIP OF CERTAIN BENEFIC...,,PART III/nITEM 12. SECURITY OWNERSHIP OF CERTA...
170,PART III,ITEM 13. CERTAIN RELATIONSHIPS AND RELATED TRA...,,PART III/nITEM 13. CERTAIN RELATIONSHIPS AND R...
171,PART III,ITEM 14. PRINCIPAL ACCOUNTANT FEES AND SERVICES,,PART III/nITEM 14. PRINCIPAL ACCOUNTANT FEES A...
172,PART IV,ITEM 15. EXHIBIT AND FINANCIAL STATEMENT SCHED...,(a)Financial Statements and Schedules,PART IV/nITEM 15. EXHIBIT AND FINANCIAL STATEM...
173,PART IV,ITEM 15. EXHIBIT AND FINANCIAL STATEMENT SCHED...,(b)Exhibit Listing,PART IV/nITEM 15. EXHIBIT AND FINANCIAL STATEM...
174,PART IV Item 15,,,PART IV Item 15/n/n<table>\n<tr>\n<th rowspan=...
175,PART IV Item 16,ITEM 16. FORM 10-K SUMMARY,,PART IV Item 16/nITEM 16. FORM 10-K SUMMARY/nN...
176,PART IV Item 16,ITEM 16. FORM 10-K SUMMARY,SIGNATURES,PART IV Item 16/nITEM 16. FORM 10-K SUMMARY/nP...
177,SUBSIDIARIES OF REGISTRANT,,,SUBSIDIARIES OF REGISTRANT/n/nThe following is...
178,CONSENT OF INDEPENDENT REGISTERED PUBLIC ACCOU...,,,CONSENT OF INDEPENDENT REGISTERED PUBLIC ACCOU...